### ISSUE TITLE
No Ternary

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#20]
Ternary statements are abused in our codebases on occasion for very long and complex logic. I think they are not very readable. Disable it in favor of normal if else blocks.

```
a = a ? a : b
```

**Comment by gentlementlegen** [comment]
When you say `disable it` do you mean make it forbidden in the eslint rules with https://eslint.org/docs/latest/rules/no-ternary ?

I'd say that ternaries sometimes make sense, and sounds like a case by case.

**Comment by 0x4007** [comment]
Yes in eslint

**Comment by gentlementlegen** [comment]
@pavlovcik What do you think if instead of completely disabling it we enforce https://eslint.org/docs/latest/rules/no-nested-ternary and https://eslint.org/docs/latest/rules/no-unneeded-ternary ? Ternaries would still be allowed but only for simple cases with one branch. I think completely disabling them is a bit too much, because they can come handy for cases like building strings with `I have ${amount > 1 ? "many" : "no"} apples"`  for example, which would be less readable if we needed an if else.

**Comment by 0x4007** [comment]
Those are good ideas lets do that
