### ISSUE TITLE
Knip Report

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#28]
Handle all of these either by removing them (ideal) or by ignoring them etc if they must be. For example, the eslint stuff probably needs to be ignored since its not used at runtime, but instead, during commits in development. 

---

### Unused devDependencies (5)

|Filename|devDependencies|
|-|-|
|package.json|`@mswjs/data`<br/>`@types/jest`<br/>`eslint-config-prettier`<br/>`eslint-plugin-prettier`<br/>`ts-node`|

### Unlisted dependencies (1)

|Filename|unlisted|
|-|-|
|tests/main.test.ts|`@jest/globals`|

_Originally posted by @github-actions[bot] in https://github.com/ubiquity/ts-template/issues/27#issuecomment-1980187255_

**Comment by gentlementlegen** [comment]
@pavlovcik So to address all of the issues:
- Jest and Eslint related messages can be safely ignored according to the docs https://knip.dev/guides/handling-issues#eslint--jest
- `ts-node` is still needed by `jest` to understand the `.ts` config, and there seem to be no workaround for this except having a `js` file
- `@mswjs/data` is used in the code but ignored by knip because it is located in the mocks folder

What I did in the end is adding all of them to the ignored dependencies, I don't see a better solution at least for now.

Another option would be to use the new `eslint` flat configuration. But this requires to have a `js` file with the config which I know you don't like: https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#configuration-new-eslintconfigjs

**Comment by 0x4007** [comment]
Okay so regarding ts-node can we do a json config?

**Comment by gentlementlegen** [comment]
@pavlovcik Just changed the configuration of Jest to be done through a JSON file.
