### ISSUE TITLE
Automatic monthly sync

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#54]
It could be interesting to bake in a CRON job that runs once a month to attempt to sync the template. 

This will ensure that our repositories in the future are effortlessly synced. 

A pull request can be opened up against the `development` branch, and any conflicts would be expected to be manually resolved. 

Add this to our active repositories as well. I suppose a script could be made to add the action file to all of our active repositories. "Active" can be defined as updated within the last month.

**Comment by 0x4007** [comment]
> One problem to solve though is that if a specific file was deleted from the template, for example, cypress related test code on a project that has no UI, I hope that this script will not attempt to re-add the deleted file.
>
> If this problem is simple to solve then I think we should continue with this proposal. Otherwise it might make too much a mess with redundant changes.

I think that git is aware of a file that is deleted based on its timestamp, and will only add it back if the file was added (or modified?) in the `ts-template` afterwards, so this should be a non-issue!

**Comment by gentlementlegen** [comment]
Instead of doing it as a CRON once a month, couldn't we do it on changes in the main branch? This way we wouldn't miss important updates, and I don't think we change this repo very often so it should not be noisy.

**Comment by 0x4007** [comment]
> Instead of doing it as a CRON once a month, couldn't we do it on changes in the main branch? This way we wouldn't miss important updates, and I don't think we change this repo very often so it should not be noisy.

I don't understand what you mean by changes in the main branch, but the idea is that this CRON would exist in all of the repositories, and each would self sync.

**Comment by zyrafal** [comment]
https://github.com/ubiquity/ts-template/pull/56

**Comment by gentlementlegen** [comment]
We might want to add this logic to https://github.com/ubiquibot/plugin-template afterwards.

**Comment by zyrafal** [comment]
@0x4007 Why does it say "execution reverted" when I try to claim it? Do I need funds on the account to cover a fee or something?

**Comment by 0x4007** [comment]
Yes you need to pay the gas fee

**Comment by zyrafal** [comment]
@0x4007 Ummmm... Could you just send me the 0.0002 XDAI I need for the fee? I'm having trouble finding a way to transfer any funds there. I'll send it back as soon as I get my funds if it matters.
Edit: nevermind I figured it out.

**Comment by Keyrxng** [comment]
@zyrafal I'm not sure if this was resolved for you or not but this faucet will give you enough for a few transactions

https://faucet.gnosischain.com/

**Comment by Keyrxng** [comment]
Please see this issue https://github.com/ubiquity/pay.ubq.fi/issues/295. There are a lot of default things I'd have excluded from the start by default as all of these workflow installs are going to need manually customized to ignore the same things each month, or we repeat the same merge handling each month for these aspects in all repos essentially. It appears we cannot exclude via dir but it needs to be a filename and ext

- `/tests`
- `/static`
- `/build`
- `/cypress`

Could it be possible to ignore dependencies from being pulled in too, as we'll be having to handle that each month too with some repos not having a jest suite for example. 

> and any conflicts would be expected to be manually resolved.

I read this line just to make it clear I have read the convo this morning lol but if this happens every month forever surely we can optimize it further

**Comment by 0x4007** [comment]
The way git works means if you removed it once it won't come in again, unless it was re-added again afterwards in the ts-template. I verified that behavior before approving the sync script task.

**Comment by Keyrxng** [comment]
https://github.com/ubq-testing/pay.ubq.fi/commit/70318ddd86950e2d4a638ea4716e67cac98b8fdf

So if I handle this first sync PR and delete everything that I do not want merged, then the next time it runs so the 2nd PR, there won't be any of the things that I had to delete from the first PR? Is that what you mean because that's pretty cool if that works

**Comment by 0x4007** [comment]
That is how git is supposed to work.

**Comment by whilefoo** [comment]
> The way git works means if you removed it once it won't come in again, unless it was re-added again afterwards in the ts-template. I verified that behavior before approving the sync script task.

I don't understand how this would work. Every time this workflow runs `ubiquity/ts-template` is cloned and then every file is copied from the template over to the repo and then pushed. `git add .` is used so it will add all files even new ones, unless we used `git add -u .` but then any new files in the template repo won't be added to the PR.

Currently trying to test it but I can't get it working: https://github.com/ubiquity-whilefoo/test/actions/runs/10774969004/job/29878307659

**Comment by 0x4007** [comment]
I tested it before finalizing the spec. It is possible in the scenario that I tested it might not include some type of edge case. 

I did some research with ChatGPT to also verify my results.

**Comment by whilefoo** [comment]
Are we thinking of a same situation? For example:

1. I clone the `ts-template`
2. I remove `cypress` folder because I don't need it
3. I run the sync workflow
4. PR should not include `cypress` folder

In this situation the workflow did create `cypress` folder which you can see from my run above.

EDIT: ChatGPT confirmed it: https://chatgpt.com/share/fb763d6a-5bd7-46ff-8aa3-f57befdd6873

**Comment by 0x4007** [comment]
Then I must be remembering something wrong. As I understand:

A = template

1. File is in repo A, B
2. File is deleted in B
3. Sync 
4. File should not be added again because the deletion occurred after the timestamp of it being added originally (in the template.)

The comment you wrote about git add might be the solution.

**Comment by rndquu** [comment]
The [sync template](https://github.com/zyrafal/ts-template/blob/89b942ed3a2d87c00f2bf61057586e0ead5119d3/.github/workflows/sync-template.yml) workflow simply adds a mess to a repository and waste of development time.

This approach doesn't work for complex repositories because the amount of time spent for fixing merge conflicts, failing builds and broken features for [such](https://github.com/ubq-testing/pay.ubq.fi/commit/70318ddd86950e2d4a638ea4716e67cac98b8fdf) PRs is greater compared to manual adding of the missing `ts-template` features (like linters or whatever).

If some repo really need a sync with `ts-template` (What are real use cases by the way? Except for linters or knip workflows.) then in the end it must be done manually. Syncing the whole zoo of our repositories with `ts-template` on a daily basis is a hell.

We'd better delete the [sync template](https://github.com/zyrafal/ts-template/blob/89b942ed3a2d87c00f2bf61057586e0ead5119d3/.github/workflows/sync-template.yml) workflow from all of our repos.

**Comment by 0x4007** [comment]
It's supposed to be once a month and if it's a problem then the pull can be closed. I think it's worth a try because in my (limited) testing it was fine.

**Comment by 0x4007** [comment]
> We'd better delete the [sync template](https://github.com/zyrafal/ts-template/blob/89b942ed3a2d87c00f2bf61057586e0ead5119d3/.github/workflows/sync-template.yml) workflow from all of our repos.

Working on it!
